;//Map header file for CHM project
;//Automatically generated by Easy CHM.
;//Website : http://www.zipghost.com
;//Email   : webmaster@zipghost.com
;//Date    : 2019/7/31 10:37:02

;//NOTE:
;//All strings after the ";" are commnets, they will be ignored by the CHM Compiler.

#define IDH_1035	1035	; Ubuntu Server Guide index.html
#define IDH_1043	1043	; 介绍 introduction-chap\introduction-chap.html
#define IDH_1044	1044	; 支持 introduction-chap\ubuntu-support.html
#define IDH_1037	1037	; 安装 installation\installation.html
#define IDH_1042	1042	; 准备安装 installation\preparing-to-install.html
#define IDH_1039	1039	; 使用实时服务器安装程序安装 installation\installing-live-server.html
#define IDH_1038	1038	; 使用debian-installer进行安装 installation\installing-from-cd.html
#define IDH_1040	1040	; 升级 installation\installing-upgrading.html
#define IDH_1036	1036	; 高级安装 installation\advanced-installation.html
#define IDH_1041	1041	; 内核崩溃转储 installation\kernel-crash-dump.html
#define IDH_1077	1077	; 包管理 package-management\package-management.html
#define IDH_1075	1075	; 介绍 package-management\package-management-introduction.html
#define IDH_1074	1074	; 的dpkg package-management\dpkg.html
#define IDH_1070	1070	; 易于 package-management\apt.html
#define IDH_1071	1071	; 能力倾向 package-management\aptitude.html
#define IDH_1072	1072	; 自动更新 package-management\automatic-updates.html
#define IDH_1073	1073	; 组态 package-management\configuration.html
#define IDH_1076	1076	; 参考 package-management\package-management-references.html
#define IDH_1063	1063	; 联网 networking\networking.html
#define IDH_1062	1062	; 网络配置 networking\network-configuration.html
#define IDH_1065	1065	; TCP / IP networking\tcpip.html
#define IDH_1060	1060	; 动态主机配置协议（DHCP） networking\dhcp.html
#define IDH_1064	1064	; 时间同步 networking\NTP.html
#define IDH_1061	1061	; 数据平面开发套件 networking\DPDK.html
#define IDH_1014	1014	; DM-多路径 dm-multipath-chapter\dm-multipath-chapter.html
#define IDH_1013	1013	; 设备映射器多路径 dm-multipath-chapter\device-mapper-multipathing.html
#define IDH_1016	1016	; 多路径设备 dm-multipath-chapter\multipath-devices.html
#define IDH_1018	1018	; 设置DM-Multipath概述 dm-multipath-chapter\multipath-setting-up-dm-multipath.html
#define IDH_1017	1017	; DM-Multipath配置文件 dm-multipath-chapter\multipath-dm-multipath-config-file.html
#define IDH_1015	1015	; DM-Multipath管理和故障排除 dm-multipath-chapter\multipath-admin-and-troubleshooting.html
#define IDH_1080	1080	; 远程管理 remote-administration\remote-administration.html
#define IDH_1078	1078	; OpenSSH服务器 remote-administration\openssh-server.html
#define IDH_1079	1079	; 木偶 remote-administration\puppet.html
#define IDH_1081	1081	; Zentyal remote-administration\zentyal.html
#define IDH_1056	1056	; 网络身份验证 network-authentication\network-authentication.html
#define IDH_1057	1057	; OpenLDAP服务器 network-authentication\openldap-server.html
#define IDH_1058	1058	; Samba和LDAP network-authentication\samba-ldap.html
#define IDH_1055	1055	; Kerberos的 network-authentication\kerberos.html
#define IDH_1054	1054	; Kerberos和LDAP network-authentication\kerberos-ldap.html
#define IDH_1059	1059	; SSSD和Active Directory network-authentication\sssd-ad.html
#define IDH_1023	1023	; 域名服务（DNS） dns\dns.html
#define IDH_1020	1020	; 安装 dns\dns-installation.html
#define IDH_1019	1019	; 组态 dns\dns-configuration.html
#define IDH_1022	1022	; 故障排除 dns\dns-troubleshooting.html
#define IDH_1021	1021	; 参考 dns\dns-references.html
#define IDH_1094	1094	; 安全 security\security.html
#define IDH_1095	1095	; User Management security\user-management.html
#define IDH_1091	1091	; 控制台安全 security\console-security.html
#define IDH_1093	1093	; 火墙 security\firewall.html
#define IDH_1089	1089	; AppArmor的 security\apparmor.html
#define IDH_1090	1090	; 证书 security\certificates-and-security.html
#define IDH_1092	1092	; eCryptfs security\ecryptfs.html
#define IDH_1051	1051	; 监控 monitoring\monitoring.html
#define IDH_1050	1050	; 概观 monitoring\monitoring-overview.html
#define IDH_1053	1053	; Nagios的 monitoring\nagios.html
#define IDH_1052	1052	; 穆宁 monitoring\munin.html
#define IDH_1117	1117	; Web服务器 web-servers\web-servers.html
#define IDH_1112	1112	; HTTPD - Apache2 Web Server web-servers\httpd.html
#define IDH_1113	1113	; PHP - 脚本语言 web-servers\php.html
#define IDH_1115	1115	; Squid - 代理服务器 web-servers\squid.html
#define IDH_1114	1114	; Ruby on Rails web-servers\ruby-on-rails.html
#define IDH_1116	1116	; Apache Tomcat web-servers\tomcat.html
#define IDH_1010	1010	; 数据库 databases\databases.html
#define IDH_1011	1011	; MySQL的 databases\mysql.html
#define IDH_1012	1012	; PostgreSQL的 databases\postgresql.html
#define IDH_1045	1045	; LAMP应用 lamp-applications\lamp-applications.html
#define IDH_1046	1046	; 概观 lamp-applications\lamp-overview.html
#define IDH_1047	1047	; Moin Moin lamp-applications\moinmoin.html
#define IDH_1048	1048	; phpMyAdmin的 lamp-applications\phpmyadmin.html
#define IDH_1049	1049	; WordPress的 lamp-applications\wordpress.html
#define IDH_1031	1031	; 文件服务器 file-servers\file-servers.html
#define IDH_1032	1032	; FTP服务器 file-servers\ftp-server.html
#define IDH_1034	1034	; 网络文件系统（NFS） file-servers\network-file-system.html
#define IDH_1033	1033	; iSCSI启动器 file-servers\iscsi-initiator.html
#define IDH_1030	1030	; CUPS - 打印服务器 file-servers\cups.html
#define IDH_1025	1025	; 电邮服务 email-services\email-services.html
#define IDH_1029	1029	; 后缀 email-services\postfix.html
#define IDH_1026	1026	; 的exim4 email-services\exim4.html
#define IDH_1024	1024	; Dovecot服务器 email-services\dovecot-server.html
#define IDH_1028	1028	; 邮差 email-services\mailman.html
#define IDH_1027	1027	; 邮件过滤 email-services\mail-filtering.html
#define IDH_1005	1005	; 聊天应用程序 chat-servers\chat-servers.html
#define IDH_1004	1004	; 概观 chat-servers\chat-overview.html
#define IDH_1006	1006	; IRC服务器 chat-servers\irc-server.html
#define IDH_1007	1007	; Jabber Instant Messaging Server chat-servers\jabberd2-server.html
#define IDH_1102	1102	; 版本控制系统 version-control-system\version-control-system.html
#define IDH_1098	1098	; 市场 version-control-system\bazaar.html
#define IDH_1099	1099	; 混帐 version-control-system\git.html
#define IDH_1100	1100	; 颠覆 version-control-system\subversion.html
#define IDH_1101	1101	; 参考 version-control-system\version-control-ref.html
#define IDH_1088	1088	; 桑巴 samba\samba.html
#define IDH_1086	1086	; 介绍 samba\samba-introduction.html
#define IDH_1085	1085	; 文件服务器 samba\samba-fileserver.html
#define IDH_1087	1087	; 打印服务器 samba\samba-printserver.html
#define IDH_1084	1084	; 保护文件和打印服务器 samba\samba-fileprint-security.html
#define IDH_1083	1083	; 作为域控制器 samba\samba-dc.html
#define IDH_1082	1082	; Active Directory集成 samba\samba-ad-integration.html
#define IDH_1002	1002	; 备份 backups\backups.html
#define IDH_1000	1000	; Shell Scripts backups\backup-shellscripts.html
#define IDH_1003	1003	; Bacula的 backups\bacula.html
#define IDH_1001	1001	; 存档轮换 backups\backups-shellscripts-rotation.html
#define IDH_1109	1109	; 虚拟化 virtualization\virtualization.html
#define IDH_1104	1104	; libvirt的 virtualization\libvirt.html
#define IDH_1107	1107	; QEMU virtualization\qemu.html
#define IDH_1103	1103	; 云图像和uvtool virtualization\cloud-images-and-uvtool.html
#define IDH_1108	1108	; Ubuntu Cloud virtualization\ubuntucloud.html
#define IDH_1106	1106	; LXD virtualization\lxd.html
#define IDH_1105	1105	; LXC virtualization\lxc.html
#define IDH_1008	1008	; 聚类 clustering\clustering.html
#define IDH_1009	1009	; DRBD clustering\drbd.html
#define IDH_1111	1111	; VPN vpn\vpn.html
#define IDH_1110	1110	; OpenVPN的 vpn\openvpn.html
#define IDH_1068	1068	; 其他有用的应用 other-useful-applications\other-useful-applications.html
#define IDH_1069	1069	; pam motd other-useful-applications\pam_motd.html
#define IDH_1067	1067	; etckeeper other-useful-applications\etckeeper.html
#define IDH_1066	1066	; 屏风 other-useful-applications\byobu.html
#define IDH_1097	1097	; 附录 serverguide-appendix\serverguide-appendix.html
#define IDH_1096	1096	; 报告Ubuntu Server Edition中的错误 serverguide-appendix\reporting-bugs.html
