;//Map header file for CHM project
;//Automatically generated by Easy CHM.
;//Website : http://www.zipghost.com
;//Email   : webmaster@zipghost.com
;//Date    : 2019/7/31 10:58:44

;//NOTE:
;//All strings after the ";" are commnets, they will be ignored by the CHM Compiler.

#define IDH_1035	1035	; Ubuntu Server Guide index.html
#define IDH_1043	1043	; Introduction introduction-chap\introduction-chap.html
#define IDH_1044	1044	; Support introduction-chap\ubuntu-support.html
#define IDH_1037	1037	; Installation installation\installation.html
#define IDH_1042	1042	; Preparing to Install installation\preparing-to-install.html
#define IDH_1039	1039	; Installing using the live server installer installation\installing-live-server.html
#define IDH_1038	1038	; Installation using debian-installer installation\installing-from-cd.html
#define IDH_1040	1040	; Upgrading installation\installing-upgrading.html
#define IDH_1036	1036	; Advanced Installation installation\advanced-installation.html
#define IDH_1041	1041	; Kernel Crash Dump installation\kernel-crash-dump.html
#define IDH_1077	1077	; Package Management package-management\package-management.html
#define IDH_1075	1075	; Introduction package-management\package-management-introduction.html
#define IDH_1074	1074	; dpkg package-management\dpkg.html
#define IDH_1070	1070	; Apt package-management\apt.html
#define IDH_1071	1071	; Aptitude package-management\aptitude.html
#define IDH_1072	1072	; Automatic Updates package-management\automatic-updates.html
#define IDH_1073	1073	; Configuration package-management\configuration.html
#define IDH_1076	1076	; References package-management\package-management-references.html
#define IDH_1063	1063	; Networking networking\networking.html
#define IDH_1062	1062	; Network Configuration networking\network-configuration.html
#define IDH_1065	1065	; TCP/IP networking\tcpip.html
#define IDH_1060	1060	; Dynamic Host Configuration Protocol (DHCP) networking\dhcp.html
#define IDH_1064	1064	; Time Synchronization networking\NTP.html
#define IDH_1061	1061	; Data Plane Development Kit networking\DPDK.html
#define IDH_1014	1014	; DM-Multipath dm-multipath-chapter\dm-multipath-chapter.html
#define IDH_1013	1013	; Device Mapper Multipathing dm-multipath-chapter\device-mapper-multipathing.html
#define IDH_1016	1016	; Multipath Devices dm-multipath-chapter\multipath-devices.html
#define IDH_1018	1018	; Setting up DM-Multipath Overview dm-multipath-chapter\multipath-setting-up-dm-multipath.html
#define IDH_1017	1017	; The DM-Multipath Configuration File dm-multipath-chapter\multipath-dm-multipath-config-file.html
#define IDH_1015	1015	; DM-Multipath Administration and Troubleshooting dm-multipath-chapter\multipath-admin-and-troubleshooting.html
#define IDH_1080	1080	; Remote Administration remote-administration\remote-administration.html
#define IDH_1078	1078	; OpenSSH Server remote-administration\openssh-server.html
#define IDH_1079	1079	; Puppet remote-administration\puppet.html
#define IDH_1081	1081	; Zentyal remote-administration\zentyal.html
#define IDH_1056	1056	; Network Authentication network-authentication\network-authentication.html
#define IDH_1057	1057	; OpenLDAP Server network-authentication\openldap-server.html
#define IDH_1058	1058	; Samba and LDAP network-authentication\samba-ldap.html
#define IDH_1055	1055	; Kerberos network-authentication\kerberos.html
#define IDH_1054	1054	; Kerberos and LDAP network-authentication\kerberos-ldap.html
#define IDH_1059	1059	; SSSD and Active Directory network-authentication\sssd-ad.html
#define IDH_1023	1023	; Domain Name Service (DNS) dns\dns.html
#define IDH_1020	1020	; Installation dns\dns-installation.html
#define IDH_1019	1019	; Configuration dns\dns-configuration.html
#define IDH_1022	1022	; Troubleshooting dns\dns-troubleshooting.html
#define IDH_1021	1021	; References dns\dns-references.html
#define IDH_1094	1094	; Security security\security.html
#define IDH_1095	1095	; User Management security\user-management.html
#define IDH_1091	1091	; Console Security security\console-security.html
#define IDH_1093	1093	; Firewall security\firewall.html
#define IDH_1089	1089	; AppArmor security\apparmor.html
#define IDH_1090	1090	; Certificates security\certificates-and-security.html
#define IDH_1092	1092	; eCryptfs security\ecryptfs.html
#define IDH_1051	1051	; Monitoring monitoring\monitoring.html
#define IDH_1050	1050	; Overview monitoring\monitoring-overview.html
#define IDH_1053	1053	; Nagios monitoring\nagios.html
#define IDH_1052	1052	; Munin monitoring\munin.html
#define IDH_1117	1117	; Web Servers web-servers\web-servers.html
#define IDH_1112	1112	; HTTPD - Apache2 Web Server web-servers\httpd.html
#define IDH_1113	1113	; PHP - Scripting Language web-servers\php.html
#define IDH_1115	1115	; Squid - Proxy Server web-servers\squid.html
#define IDH_1114	1114	; Ruby on Rails web-servers\ruby-on-rails.html
#define IDH_1116	1116	; Apache Tomcat web-servers\tomcat.html
#define IDH_1010	1010	; Databases databases\databases.html
#define IDH_1011	1011	; MySQL databases\mysql.html
#define IDH_1012	1012	; PostgreSQL databases\postgresql.html
#define IDH_1045	1045	; LAMP Applications lamp-applications\lamp-applications.html
#define IDH_1046	1046	; Overview lamp-applications\lamp-overview.html
#define IDH_1047	1047	; Moin Moin lamp-applications\moinmoin.html
#define IDH_1048	1048	; phpMyAdmin lamp-applications\phpmyadmin.html
#define IDH_1049	1049	; WordPress lamp-applications\wordpress.html
#define IDH_1031	1031	; File Servers file-servers\file-servers.html
#define IDH_1032	1032	; FTP Server file-servers\ftp-server.html
#define IDH_1034	1034	; Network File System (NFS) file-servers\network-file-system.html
#define IDH_1033	1033	; iSCSI Initiator file-servers\iscsi-initiator.html
#define IDH_1030	1030	; CUPS - Print Server file-servers\cups.html
#define IDH_1025	1025	; Email Services email-services\email-services.html
#define IDH_1029	1029	; Postfix email-services\postfix.html
#define IDH_1026	1026	; Exim4 email-services\exim4.html
#define IDH_1024	1024	; Dovecot Server email-services\dovecot-server.html
#define IDH_1028	1028	; Mailman email-services\mailman.html
#define IDH_1027	1027	; Mail Filtering email-services\mail-filtering.html
#define IDH_1005	1005	; Chat Applications chat-servers\chat-servers.html
#define IDH_1004	1004	; Overview chat-servers\chat-overview.html
#define IDH_1006	1006	; IRC Server chat-servers\irc-server.html
#define IDH_1007	1007	; Jabber Instant Messaging Server chat-servers\jabberd2-server.html
#define IDH_1102	1102	; Version Control System version-control-system\version-control-system.html
#define IDH_1098	1098	; Bazaar version-control-system\bazaar.html
#define IDH_1099	1099	; Git version-control-system\git.html
#define IDH_1100	1100	; Subversion version-control-system\subversion.html
#define IDH_1101	1101	; References version-control-system\version-control-ref.html
#define IDH_1088	1088	; Samba samba\samba.html
#define IDH_1086	1086	; Introduction samba\samba-introduction.html
#define IDH_1085	1085	; File Server samba\samba-fileserver.html
#define IDH_1087	1087	; Print Server samba\samba-printserver.html
#define IDH_1084	1084	; Securing File and Print Server samba\samba-fileprint-security.html
#define IDH_1083	1083	; As a Domain Controller samba\samba-dc.html
#define IDH_1082	1082	; Active Directory Integration samba\samba-ad-integration.html
#define IDH_1002	1002	; Backups backups\backups.html
#define IDH_1000	1000	; Shell Scripts backups\backup-shellscripts.html
#define IDH_1003	1003	; Bacula backups\bacula.html
#define IDH_1001	1001	; Archive Rotation backups\backups-shellscripts-rotation.html
#define IDH_1109	1109	; Virtualization virtualization\virtualization.html
#define IDH_1104	1104	; libvirt virtualization\libvirt.html
#define IDH_1107	1107	; Qemu virtualization\qemu.html
#define IDH_1103	1103	; Cloud images and uvtool virtualization\cloud-images-and-uvtool.html
#define IDH_1108	1108	; Ubuntu Cloud virtualization\ubuntucloud.html
#define IDH_1106	1106	; LXD virtualization\lxd.html
#define IDH_1105	1105	; LXC virtualization\lxc.html
#define IDH_1008	1008	; Clustering clustering\clustering.html
#define IDH_1009	1009	; DRBD clustering\drbd.html
#define IDH_1111	1111	; VPN vpn\vpn.html
#define IDH_1110	1110	; OpenVPN vpn\openvpn.html
#define IDH_1068	1068	; Other Useful Applications other-useful-applications\other-useful-applications.html
#define IDH_1069	1069	; pam motd other-useful-applications\pam_motd.html
#define IDH_1067	1067	; etckeeper other-useful-applications\etckeeper.html
#define IDH_1066	1066	; Byobu other-useful-applications\byobu.html
#define IDH_1097	1097	; Appendix serverguide-appendix\serverguide-appendix.html
#define IDH_1096	1096	; Reporting Bugs in Ubuntu Server Edition serverguide-appendix\reporting-bugs.html
